#!/bin/bash

cd $(dirname $(readlink -f $0))

case "$1" in

clean)
	./gradlew clean
	;;

build)
	./gradlew build
	;;

test)
	./gradlew test
	;;

analysis)
	./gradlew lint
	;;

deploy)
	./gradlew assemble
	;;

esac
