#!/bin/bash

cd $(dirname $(readlink -f $0))

case "$1" in

init)
	meteor update
	meteor npm update
	;;

clean)
	;;

build)
	meteor build .
	;;

test)
	;;

analysis)
	meteor lint
	;;

deploy)
	;;

esac
